[project]
name = "operational-research"
version = "0.1.0"
description = "Operational Research implementations."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "tabulate>=0.9.0",
]
